#!/usr/bin/env python3
"""
Schema export endpoint for complete database structure backup.

**Purpose:** Download full MySQL schema (DDL: tables, views, triggers, procedures, functions).
Works on Azure (no binary deps) and local dev environments.

**Includes:**
- CREATE TABLE statements (all tables in order)
- CREATE VIEW statements (if any views exist)
- CREATE TRIGGER statements (if any triggers exist)
- CREATE PROCEDURE statements (if any procedures exist)
- CREATE FUNCTION statements (if any functions exist)
- Column reference comments (for V11 schema redesign)
- Timestamp of export for audit trail

**Usage:**
    curl https://<web-app>/api/export-schema > db/schema_snapshot.sql
    # Or via browser: https://<web-app>/api/export-schema

**After schema export:**
    1. Review the downloaded schema_snapshot.sql
    2. Update with new column names (submissions table rename)
    3. Commit: git add db/schema_snapshot.sql && git commit -m "chore: update schema snapshot"
    4. Once complete, optionally remove this endpoint (delete api_schema.py + remove blueprint)

**Note:** This endpoint is NOT guarded by authentication—keep it private or remove after use.
"""

from flask import Blueprint, Response
import subprocess
import os
import mysql.connector
from mysql.connector import ProgrammingError

schema_bp = Blueprint('schema', __name__, url_prefix='/api')


def _get_mysql_credentials():
    """Extract MySQL creds from env. Raise ValueError if missing."""
    host = os.environ.get('MYSQL_HOST')
    user = os.environ.get('MYSQL_USER')
    password = os.environ.get('MYSQL_PASSWORD')
    database = os.environ.get('MYSQL_DATABASE', 'mmrdb')

    if not all([host, user, password]):
        raise ValueError(
            'Missing MySQL env vars: MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD. '
            'Set in Azure App Settings or local .env.local'
        )

    return host, user, password, database


def _export_via_mysqldump():
    """Try mysqldump first (local dev with mysql-client installed)."""
    try:
        host, user, password, database = _get_mysql_credentials()
        result = subprocess.run(
            [
                'mysqldump',
                f'--host={host}',
                f'--user={user}',
                f'--password={password}',
                '--no-data',
                database
            ],
            capture_output=True,
            text=True,
            check=True,
            timeout=30
        )
        return result.stdout
    except FileNotFoundError:
        return None  # mysqldump not available, fall back to Python
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f'mysqldump failed: {e.stderr}')


def _export_via_connector():
    """Fall back to mysql-connector-python (works everywhere, including Azure)."""
    host, user, password, database = _get_mysql_credentials()

    conn = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    cursor = conn.cursor()

    try:
        # Get all CREATE TABLE statements
        cursor.execute("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME", (database,))
        tables = [row[0] for row in cursor.fetchall()]

        sql_lines = [f'-- Schema export for {database}\n']
        sql_lines.append(f'-- Generated by MMR Admin schema export endpoint\n')
        sql_lines.append(f'-- Timestamp: {_get_timestamp()}\n')
        sql_lines.append(f'-- Includes: Tables, Views, Triggers, Procedures, Functions, Column metadata\n\n')

        # 1. Export CREATE TABLE statements
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- TABLES\n')
        sql_lines.append('-- ============================================================================\n\n')

        for table in tables:
            cursor.execute(f"SHOW CREATE TABLE `{table}`")
            create_statement = cursor.fetchone()[1]
            sql_lines.append(create_statement + ';\n\n')

        # 2. Export CREATE VIEW statements
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- VIEWS\n')
        sql_lines.append('-- ============================================================================\n\n')

        cursor.execute("""
            SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS
            WHERE TABLE_SCHEMA = %s ORDER BY TABLE_NAME
        """, (database,))
        views = [row[0] for row in cursor.fetchall()]

        if views:
            for view in views:
                cursor.execute(f"SHOW CREATE VIEW `{view}`")
                view_result = cursor.fetchone()
                if view_result:
                    # SHOW CREATE VIEW returns: (database, view_name, charset, CREATE_VIEW_statement)
                    create_statement = view_result[3]
                    sql_lines.append(create_statement + ';\n\n')
        else:
            sql_lines.append('-- No views defined\n\n')

        # 3. Export TRIGGERS (if any)
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- TRIGGERS\n')
        sql_lines.append('-- ============================================================================\n\n')

        cursor.execute("""
            SELECT TRIGGER_NAME, TRIGGER_SCHEMA FROM INFORMATION_SCHEMA.TRIGGERS
            WHERE TRIGGER_SCHEMA = %s ORDER BY TRIGGER_NAME
        """, (database,))
        triggers = [(row[0], row[1]) for row in cursor.fetchall()]

        if triggers:
            for trigger_name, trigger_schema in triggers:
                cursor.execute(f"SHOW CREATE TRIGGER `{trigger_name}`")
                trigger_result = cursor.fetchone()
                if trigger_result:
                    # SHOW CREATE TRIGGER returns: (trigger, sql_mode, SQL)
                    create_statement = trigger_result[2]
                    sql_lines.append(create_statement + ';\n\n')
        else:
            sql_lines.append('-- No triggers defined\n\n')

        # 4. Export PROCEDURES (if any)
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- PROCEDURES\n')
        sql_lines.append('-- ============================================================================\n\n')

        cursor.execute("""
            SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
            WHERE ROUTINE_SCHEMA = %s AND ROUTINE_TYPE = 'PROCEDURE'
            ORDER BY ROUTINE_NAME
        """, (database,))
        procedures = [row[0] for row in cursor.fetchall()]

        if procedures:
            for proc_name in procedures:
                cursor.execute(f"SHOW CREATE PROCEDURE `{proc_name}`")
                proc_result = cursor.fetchone()
                if proc_result:
                    # SHOW CREATE PROCEDURE returns: (database, procedure_name, charset, CREATE_PROCEDURE_statement)
                    create_statement = proc_result[3]
                    sql_lines.append(create_statement + ';\n\n')
        else:
            sql_lines.append('-- No procedures defined\n\n')

        # 5. Export FUNCTIONS (if any)
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- FUNCTIONS\n')
        sql_lines.append('-- ============================================================================\n\n')

        cursor.execute("""
            SELECT ROUTINE_NAME FROM INFORMATION_SCHEMA.ROUTINES
            WHERE ROUTINE_SCHEMA = %s AND ROUTINE_TYPE = 'FUNCTION'
            ORDER BY ROUTINE_NAME
        """, (database,))
        functions = [row[0] for row in cursor.fetchall()]

        if functions:
            for func_name in functions:
                cursor.execute(f"SHOW CREATE FUNCTION `{func_name}`")
                func_result = cursor.fetchone()
                if func_result:
                    # SHOW CREATE FUNCTION returns: (database, function_name, charset, CREATE_FUNCTION_statement)
                    create_statement = func_result[3]
                    sql_lines.append(create_statement + ';\n\n')
        else:
            sql_lines.append('-- No functions defined\n\n')

        # 6. Column metadata (informational comment for reference)
        sql_lines.append('-- ============================================================================\n')
        sql_lines.append('-- COLUMN REFERENCE (for schema design)\n')
        sql_lines.append('-- ============================================================================\n\n')
        sql_lines.append('-- Table: submissions (formerly webapp_events)\n')
        sql_lines.append('-- Columns: SubmissionID, SubmissionType, SubmittedAt, ExpirationTime, MemberID,\n')
        sql_lines.append('--          Email, PaymentIntent, Amount, PaymentMethod, PayerName, MemoField,\n')
        sql_lines.append('--          Last4Digits, FamilyMemberEmails, Status, MatchedMessageId,\n')
        sql_lines.append('--          MatchedTransactionNumber, AdminApprover, ApprovedAt, Notes,\n')
        sql_lines.append('--          PaymentDate, ScreenshotId, GDriveFilePath, OCRText, OCRProcessedAt,\n')
        sql_lines.append('--          CreatedAt, UpdatedAt, timestamp_unix, expires_at_unix, approval_date_unix\n\n')

        return ''.join(sql_lines)

    finally:
        cursor.close()
        conn.close()


def _get_timestamp():
    """Return current UTC timestamp for schema export."""
    from datetime import datetime
    return datetime.utcnow().isoformat() + ' UTC'


@schema_bp.route('/export-schema', methods=['GET'])
def export_schema():
    """
    Export DB schema via mysqldump (or python connector fallback).
    Returns SQL DDL for all tables (no data).

    Response: text/plain SQL file ready to save.
    Error: JSON with error message if export fails.
    """
    try:
        # Try mysqldump first (faster, local dev with mysql-client)
        schema_sql = _export_via_mysqldump()

        # Fall back to Python connector (works on Azure, no binary deps)
        if schema_sql is None:
            schema_sql = _export_via_connector()

        # Return as downloadable file
        return Response(
            schema_sql,
            mimetype='text/plain',
            headers={
                'Content-Disposition': 'attachment; filename="schema_snapshot.sql"'
            }
        )

    except ValueError as e:
        return {'error': str(e)}, 400
    except mysql.connector.Error as e:
        return {'error': f'MySQL connection failed: {e.msg}'}, 500
    except Exception as e:
        return {'error': f'Unexpected error: {str(e)}'}, 500


@schema_bp.route('/export-schema-info', methods=['GET'])
def export_schema_info():
    """
    Quick info endpoint — schema export is available at /api/export-schema.

    REMINDER: This endpoint should be removed after schema is exported.
    """
    return {
        'endpoint': '/api/export-schema',
        'method': 'GET',
        'description': 'Downloads full MySQL schema (DDL only, no data)',
        'curl_example': 'curl https://<host>/api/export-schema > db/schema_snapshot.sql',
        'status': '⚠️  TEMPORARY — delete api_schema.py and remove blueprint registration after use'
    }, 200
