#!/usr/bin/env python3
"""
Temporary schema export endpoint for database backups.

**IMPORTANT:** This endpoint is meant to be temporary. Delete after use.
It allows direct HTTP download of the MySQL schema (no data).

Designed to work on Azure (no local binary deps) and local dev.

Usage:
    curl https://<web-app>/api/export-schema > db/schema_snapshot.sql
    # Then remove this file and the blueprint registration from app.py
"""

from flask import Blueprint, Response
import subprocess
import os
import mysql.connector
from mysql.connector import ProgrammingError

schema_bp = Blueprint('schema', __name__, url_prefix='/api')


def _get_mysql_credentials():
    """Extract MySQL creds from env. Raise ValueError if missing."""
    host = os.environ.get('MYSQL_HOST')
    user = os.environ.get('MYSQL_USER')
    password = os.environ.get('MYSQL_PASSWORD')
    database = os.environ.get('MYSQL_DATABASE', 'mmrdb')

    if not all([host, user, password]):
        raise ValueError(
            'Missing MySQL env vars: MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD. '
            'Set in Azure App Settings or local .env.local'
        )

    return host, user, password, database


def _export_via_mysqldump():
    """Try mysqldump first (local dev with mysql-client installed)."""
    try:
        host, user, password, database = _get_mysql_credentials()
        result = subprocess.run(
            [
                'mysqldump',
                f'--host={host}',
                f'--user={user}',
                f'--password={password}',
                '--no-data',
                database
            ],
            capture_output=True,
            text=True,
            check=True,
            timeout=30
        )
        return result.stdout
    except FileNotFoundError:
        return None  # mysqldump not available, fall back to Python
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f'mysqldump failed: {e.stderr}')


def _export_via_connector():
    """Fall back to mysql-connector-python (works everywhere, including Azure)."""
    host, user, password, database = _get_mysql_credentials()

    conn = mysql.connector.connect(
        host=host,
        user=user,
        password=password,
        database=database
    )
    cursor = conn.cursor()

    try:
        # Get all CREATE TABLE statements
        cursor.execute("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = %s", (database,))
        tables = [row[0] for row in cursor.fetchall()]

        sql_lines = [f'-- Schema export for {database}\n']
        sql_lines.append('-- Generated by MMR Admin schema export endpoint\n\n')

        for table in tables:
            cursor.execute(f"SHOW CREATE TABLE `{table}`")
            create_statement = cursor.fetchone()[1]
            sql_lines.append(create_statement + ';\n\n')

        return ''.join(sql_lines)

    finally:
        cursor.close()
        conn.close()


@schema_bp.route('/export-schema', methods=['GET'])
def export_schema():
    """
    Export DB schema via mysqldump (or python connector fallback).
    Returns SQL DDL for all tables (no data).

    Response: text/plain SQL file ready to save.
    Error: JSON with error message if export fails.
    """
    try:
        # Try mysqldump first (faster, local dev with mysql-client)
        schema_sql = _export_via_mysqldump()

        # Fall back to Python connector (works on Azure, no binary deps)
        if schema_sql is None:
            schema_sql = _export_via_connector()

        # Return as downloadable file
        return Response(
            schema_sql,
            mimetype='text/plain',
            headers={
                'Content-Disposition': 'attachment; filename="schema_snapshot.sql"'
            }
        )

    except ValueError as e:
        return {'error': str(e)}, 400
    except mysql.connector.Error as e:
        return {'error': f'MySQL connection failed: {e.msg}'}, 500
    except Exception as e:
        return {'error': f'Unexpected error: {str(e)}'}, 500


@schema_bp.route('/export-schema-info', methods=['GET'])
def export_schema_info():
    """
    Quick info endpoint — schema export is available at /api/export-schema.

    REMINDER: This endpoint should be removed after schema is exported.
    """
    return {
        'endpoint': '/api/export-schema',
        'method': 'GET',
        'description': 'Downloads full MySQL schema (DDL only, no data)',
        'curl_example': 'curl https://<host>/api/export-schema > db/schema_snapshot.sql',
        'status': '⚠️  TEMPORARY — delete api_schema.py and remove blueprint registration after use'
    }, 200
